<?php

namespace machbarmacher\GdprDump\ColumnTransformer\Plugins;

use Faker\Factory;
use machbarmacher\GdprDump\ColumnTransformer\ColumnTransformer;

/**
 * Transformer that generates fake data using the Faker library.
 */
class FakerColumnTransformer extends ColumnTransformer {

  /**
   * The Faker generator instance.
   *
   * @var \Faker\Generator
   */
  private static $generator;

  /**
   * Maps legacy formatter names to their Faker equivalents.
   *
   * @var array
   */
  private static $formatterTansformerMap = [
    'longText' => 'paragraph',
    'number' => 'randomNumber',
    'randomText' => 'sentence',
    'text' => 'sentence',
    'uri' => 'url',
  ];

  /**
   * Returns the supported formatter names.
   */
  protected function getSupportedFormatters() {
    return array_keys(self::$formatterTansformerMap);
  }

  /**
   * Constructs a FakerColumnTransformer and initialises the Faker generator.
   */
  public function __construct($locale) {
    if (!isset(self::$generator)) {
      self::$generator = Factory::create($locale);
      foreach (self::$generator->getProviders() as $provider) {
        $clazz = new \ReflectionClass($provider);
        $methods = $clazz->getMethods(\ReflectionMethod::IS_PUBLIC);
        foreach ($methods as $m) {
          if (strpos($m->name, '__') === 0) {
            continue;
          }
          self::$formatterTansformerMap[$m->name] = $m->name;
        }
      }
    }
  }

  /**
   * Returns a fake value generated by Faker for the given expression.
   */
  public function getValue($expression) {
    if (isset($expression['modifier'])) {
      $modifier = $expression['modifier'];
      return self::$generator->{$modifier}()->format(self::$formatterTansformerMap[$expression['formatter']]);
    }
    return self::$generator->format(self::$formatterTansformerMap[$expression['formatter']]);
  }

}
